# This is a basic workflow to help you get started with Actions

name: CI

env:
  ARTIFACTORY_URL: http://34.100.254.109
  ARTIFACTORY_USER: admin
  ARTIFACTORY_PASS: ${{ secrets.JFROG_HTTP_PASSWORD }}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: jfrog/setup-jfrog-cli@v1

      # Runs a set of commands using the runners shell
      - name: Install Helm and Jfrog CLI
        run: |
          sudo apt-get update -y
          sudo apt-get install curl -y
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          sudo curl -fL https://getcli.jfrog.io | sh

      # Runs a set of commands using the runners shell
      - name: Connect to Jfrog Artifactory using Jfrog CLI
        run: |
          ./jfrog c add --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASS
          ./jfrog c show

      - uses: actions/checkout@v3
      - name: Package HELM Chart and Add the artifactory repo
        run: |
          helm package hello-nginx
          helm repo add slipway-helm ${ARTIFACTORY_URL}/artifactory/api/helm/slipway-helm --username admin --password $ARTIFACTORY_PASS
        
      - name: Upload helm package to artifactory using jf cmd
        run: ./jfrog u "(*).tgz" $ARTIFACTORY_URL/artifactory/api/helm/slipway-helm/helm-nginx-1.0.${{ github.run_id }} --recursive=false
